<?php
// i18n-map.php @generated by automattic/jetpack-composer-plugin
return array(
  'domain' => 'lifetime-subscriptions-for-woocommerce',
  'type' => 'plugins',
  'packages' => array(
    'jetpack-assets' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-assets',
      'ver' => '2.3.8',
    ),
    'wp-dashboard-widget-news' => array(
      'path' => 'jetpack_vendor/quadlayers/wp-dashboard-widget-news',
      'ver' => '1.0.9',
    ),
    'wp-notice-plugin-required' => array(
      'path' => 'jetpack_vendor/quadlayers/wp-notice-plugin-required',
      'ver' => '2.0.7',
    ),
    'wp-plugin-table-links' => array(
      'path' => 'jetpack_vendor/quadlayers/wp-plugin-table-links',
      'ver' => '1.0.7',
    ),
  ),
);
